title: Elizabeth de Sa e Silva # your name (or website title) here
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computer Science + Astronomy UIUC Class of 2020
  <br><br>

  <br><br>
  <a href="https://www.linkedin.com/in/elizabeth-de-sa-e-silva-a54b21172/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
